In [9]:
from pathlib import Path
import pandas as pd
from pandas import DataFrame

In [10]:
ruta = "datos/datos_transfermarkt/players.csv"
df = pd.read_csv(ruta)
df.head()

,player_id,first_name,last_name,name,last_season,current_club_id,player_code,country_of_birth,city_of_birth,country_of_citizenship,...,agent_name,image_url,international_caps,international_goals,current_national_team_id,url,current_club_domestic_competition_id,current_club_name,market_value_in_eur,highest_market_value_in_eur
0,10,Miroslav,Klose,Miroslav Klose,2015,398,miroslav-klose,Poland,Opole,Germany,...,ASBW Sport Marketing,https://img.a.transfermarkt.technology/portrai...,NaN,NaN,NaN,https://www.transfermarkt.co.uk/miroslav-klose...,IT1,Società Sportiva Lazio S.p.A.,1000000.0,30000000.0
1,26,Roman,Weidenfeller,Roman Weidenfeller,2017,16,roman-weidenfeller,Germany,Diez,Germany,...,Neubauer 13 GmbH,https://img.a.transfermarkt.technology/portrai...,NaN,NaN,NaN,https://www.transfermarkt.co.uk/roman-weidenfe...,L1,Borussia Dortmund,750000.0,8000000.0
2,65,Dimitar,Berbatov,Dimitar Berbatov,2015,1091,dimitar-berbatov,Bulgaria,Blagoevgrad,Bulgaria,...,CSKA-AS-23 Ltd.,https://img.a.transfermarkt.technology/portrai...,NaN,NaN,NaN,https://www.transfermarkt.co.uk/dimitar-berbat...,GR1,Panthessalonikios Athlitikos Omilos Konstantin...,1000000.0,34500000.0
3,77,NaN,Lúcio,Lúcio,2012,506,lucio,Brazil,Brasília,Brazil,...,NaN,https://img.a.transfermarkt.technology/portrai...,NaN,NaN,NaN,https://www.transfermarkt.co.uk/lucio/profil/s...,IT1,Juventus FC,200000.0,24500000.0
4,80,Tom,Starke,Tom Starke,2017,27,tom-starke,East Germany (GDR),Freital,Germany,...,IFM,https://img.a.transfermarkt.technology/portrai...,NaN,NaN,NaN,https://www.transfermarkt.co.uk/tom-starke/pro...,L1,Bayern Munich,100000.0,3000000.0

In [11]:
def eliminar_columnas(df: DataFrame, lista_columnas: list[str]) -> DataFrame:
    return df.drop(lista_columnas, axis=1)

eliminar_columnas(df, ["image_url", "url"])

,player_id,first_name,last_name,name,last_season,current_club_id,player_code,country_of_birth,city_of_birth,country_of_citizenship,...,height_in_cm,contract_expiration_date,agent_name,international_caps,international_goals,current_national_team_id,current_club_domestic_competition_id,current_club_name,market_value_in_eur,highest_market_value_in_eur
0,10,Miroslav,Klose,Miroslav Klose,2015,398,miroslav-klose,Poland,Opole,Germany,...,184.0,NaN,ASBW Sport Marketing,NaN,NaN,NaN,IT1,Società Sportiva Lazio S.p.A.,1000000.0,30000000.0
1,26,Roman,Weidenfeller,Roman Weidenfeller,2017,16,roman-weidenfeller,Germany,Diez,Germany,...,190.0,NaN,Neubauer 13 GmbH,NaN,NaN,NaN,L1,Borussia Dortmund,750000.0,8000000.0
2,65,Dimitar,Berbatov,Dimitar Berbatov,2015,1091,dimitar-berbatov,Bulgaria,Blagoevgrad,Bulgaria,...,NaN,NaN,CSKA-AS-23 Ltd.,NaN,NaN,NaN,GR1,Panthessalonikios Athlitikos Omilos Konstantin...,1000000.0,34500000.0
3,77,NaN,Lúcio,Lúcio,2012,506,lucio,Brazil,Brasília,Brazil,...,NaN,NaN,NaN,NaN,NaN,NaN,IT1,Juventus FC,200000.0,24500000.0
4,80,Tom,Starke,Tom Starke,2017,27,tom-starke,East Germany (GDR),Freital,Germany,...,194.0,NaN,IFM,NaN,NaN,NaN,L1,Bayern Munich,100000.0,3000000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50144,1546617,Yahya Mousa,Gharawi,Yahya Mousa Gharawi,2025,34911,yahya-mousa-gharawi,NaN,NaN,Saudi Arabia,...,NaN,NaN,NaN,NaN,NaN,NaN,SA1,Neom Sports Club,NaN,NaN
50145,1547421,Szabolcs,Nyitra,Szabolcs Nyitra,2025,37255,szabolcs-nyitra,NaN,NaN,Romania,...,NaN,NaN,NaN,NaN,NaN,NaN,RO1,FK Csikszereda Miercurea Ciuc,NaN,NaN
50146,1548905,Iustin,Filote,Iustin Filote,2025,8818,iustin-filote,NaN,NaN,Romania,...,NaN,NaN,NaN,NaN,NaN,NaN,RO1,FC Botosani,NaN,NaN
50147,1550699,Vukasin,Zdravkovic,Vukasin Zdravkovic,2025,7567,vukasin-zdravkovic,NaN,NaN,Serbia,...,NaN,NaN,NaN,NaN,NaN,NaN,SER1,FK Radnicki Nis,NaN,NaN
50148,1555760,Aidan,Melville,Aidan Melville,2025,32371,aidan-melville,United States,"Portland, Maine",Puerto Rico,...,180.0,NaN,NaN,1.0,0.0,17759.0,NaN,NaN,NaN,NaN